const SUPABASE_URL='https://voumtuvtbrkbdmkqfmzy.supabase.co';
const SUPABASE_ANON_KEY='sb_publishable_KO5mI0KB4Ou5uvuTDAjk0A_eU63pJYu';
const COMMENTS_TABLE='comments';
const COMMENT_STATUS_ON_SUBMIT='approved';
const PREFIX='__MRNOKK_COMMENT_JSON__';
const EMOJIS=['😀','😂','🤣','😍','😎','🤔','😭','😡','👍','👏','🎉','❤️'];
const GIFS=[
{id:'laughing-cat',label:'笑出声',url:'https://media.tenor.com/2roX3uxz_68AAAAC/cat-space.gif'},
{id:'dancing-banana',label:'开心摇摆',url:'https://media.giphy.com/media/IB9foBA4PVkKA/giphy.gif'},
{id:'mind-blown',label:'震惊',url:'https://media.giphy.com/media/Um3ljJl8jrnHy/giphy.gif'},
{id:'applause',label:'鼓掌',url:'https://media.giphy.com/media/l3q2XhfQ8oCkm1Ts4/giphy.gif'},
{id:'popcorn',label:'吃瓜',url:'https://media.giphy.com/media/tyqcJoNjNv0Fq/giphy.gif'},
{id:'facepalm',label:'无语',url:'https://media.giphy.com/media/TJawtKM6OCKkvwCIqX/giphy.gif'}
];
const state={pagePath:(location.pathname.split('/').pop()||'index.html').replace(/\.html$/i,'')||'index'};
const ok=()=>SUPABASE_URL.startsWith('https://')&&!SUPABASE_URL.includes('YOUR_PROJECT_ID')&&!SUPABASE_ANON_KEY.includes('YOUR_SUPABASE_ANON_PUBLIC_KEY');
const esc=v=>String(v||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
const gif=id=>GIFS.find(g=>g.id===id)||null;
const ep=q=>`${SUPABASE_URL}/rest/v1/${COMMENTS_TABLE}${q||''}`;
const headers=(h={})=>({apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${SUPABASE_ANON_KEY}`,...h});
function time(v){try{return new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(v));}catch{return''}}
function pack(text,gifId=''){return PREFIX+JSON.stringify({text,gif:gif(gifId)?gifId:''})}
function unpack(v){const raw=String(v||'');if(!raw.startsWith(PREFIX))return{text:raw,gif:''};try{const p=JSON.parse(raw.slice(PREFIX.length));return{text:String(p.text||''),gif:gif(p.gif)?p.gif:''}}catch{return{text:raw,gif:''}}}
function css(){if(document.getElementById('comment-system-styles'))return;const s=document.createElement('style');s.id='comment-system-styles';s.textContent=`
.blog-comments{margin-top:3rem;background:var(--surface-card);border:1px solid var(--hairline);border-radius:var(--rounded-lg);padding:2rem}.blog-comments__title{color:var(--ink);font-size:1.25rem;margin-bottom:1rem}.blog-comments__hint{color:var(--muted);font-size:.9rem;margin-bottom:1rem}.blog-comments__form{display:grid;gap:.85rem;margin-bottom:1.5rem}.blog-comments__row{display:grid;grid-template-columns:1fr 1fr;gap:.85rem}.blog-comments input,.blog-comments textarea{width:100%;border:1px solid var(--hairline);border-radius:var(--rounded-md);background:var(--canvas);color:var(--ink);padding:.75rem .9rem;font:inherit;outline:none}.blog-comments textarea{min-height:120px;resize:vertical}.blog-comments input::placeholder,.blog-comments textarea::placeholder{color:var(--muted-soft)}.blog-comments input:focus,.blog-comments textarea:focus{border-color:var(--primary);background:var(--canvas);box-shadow:0 0 0 3px rgba(10,10,10,.08)}
.comment-tools{position:relative;display:grid;gap:.85rem}.tool-toggle{justify-self:start;min-height:44px;border:1px solid var(--hairline);border-radius:var(--rounded-pill);background:var(--canvas);color:var(--ink);padding:.55rem 1rem;cursor:pointer;font:inherit;font-weight:500}.tool-toggle:hover{background:var(--surface-soft)}.tool-panel{display:none;position:absolute;left:0;top:52px;z-index:30;width:min(640px,100%);max-height:70vh;overflow:auto;border:1px solid var(--hairline);border-radius:var(--rounded-lg);background:var(--surface-soft);box-shadow:0 18px 48px rgba(0,0,0,.1);padding:1rem}.tool-panel.is-open{display:grid;gap:.95rem}.comment-tools__title{color:var(--muted);font-size:.85rem;font-weight:600}.emoji-picker{display:flex;flex-wrap:wrap;gap:.45rem}.emoji-button{width:44px;height:44px;border:1px solid var(--hairline);border-radius:var(--rounded-sm);background:var(--canvas);cursor:pointer;font-size:1.25rem}.emoji-button:hover{background:var(--surface-soft)}.gif-picker{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:.75rem}.gif-option{border:1px solid var(--hairline);border-radius:var(--rounded-md);background:var(--canvas);padding:.45rem;color:var(--ink);cursor:pointer;text-align:left}.gif-option:hover{background:var(--surface-soft)}.gif-option.is-selected{border-color:var(--primary);box-shadow:0 0 0 3px rgba(10,10,10,.08)}.gif-option img,.comment-gif img{display:block;width:100%;object-fit:cover;border-radius:9px;background:rgba(0,0,0,.08)}.gif-option img{aspect-ratio:16/10}.gif-option span{display:block;margin-top:.4rem;color:var(--muted);font-size:.78rem;text-align:center}.selected-gif{display:none;align-items:center;justify-content:space-between;gap:1rem;border:1px solid var(--brand-ochre);border-radius:var(--rounded-md);background:var(--surface-soft);padding:.65rem .85rem;color:var(--ink)}.selected-gif.is-visible{display:flex}.selected-gif__remove{min-height:36px;border:1px solid var(--hairline);border-radius:var(--rounded-pill);background:var(--canvas);color:var(--ink);padding:.35rem .75rem;cursor:pointer}
.blog-comments__submit{justify-self:start;min-height:44px;border:0;border-radius:var(--rounded-pill);padding:.7rem 1.25rem;background:var(--primary);color:var(--on-primary);font:inherit;font-weight:600;cursor:pointer}.blog-comments__submit:disabled{cursor:not-allowed;opacity:.65}.blog-comments__message{min-height:1.4rem;color:var(--muted);font-size:.9rem}.blog-comments__message.is-error{color:var(--error)}.blog-comments__message.is-success{color:var(--success)}.blog-comments__list{display:grid;gap:1rem}.comment-item{border:1px solid var(--hairline-soft);border-radius:var(--rounded-md);background:var(--surface-soft);padding:1rem}.comment-header{display:flex;justify-content:space-between;gap:1rem;margin-bottom:.55rem}.comment-author{color:var(--ink);font-weight:600}.comment-time{color:var(--muted);font-size:.82rem;white-space:nowrap}.comment-content{color:var(--body);white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.7}.comment-gif{max-width:320px;margin-top:.85rem}.comment-gif img{max-height:220px;border:1px solid var(--hairline)}.blog-comments__empty{color:var(--muted);text-align:center;padding:1rem 0}@media(max-width:640px){.blog-comments{padding:1.25rem}.blog-comments__row{grid-template-columns:1fr}.comment-header{flex-direction:column;gap:.25rem}.gif-picker{grid-template-columns:repeat(2,minmax(0,1fr))}.selected-gif{align-items:flex-start;flex-direction:column}.tool-panel{position:fixed;left:1rem;right:1rem;top:50%;transform:translateY(-50%);width:auto}}
`;document.head.appendChild(s)}
function msg(t,type=''){const e=document.querySelector('[data-comment-message]');if(!e)return;e.textContent=t;e.classList.toggle('is-error',type==='error');e.classList.toggle('is-success',type==='success')}
function renderBox(c){c.classList.add('blog-comments');c.innerHTML=`<h3 class="blog-comments__title">评论</h3><p class="blog-comments__hint">填写昵称即可留言。邮箱不会公开，可不填。GIF 只能从下方固定选项里选择。</p><form class="blog-comments__form" data-comment-form><div class="blog-comments__row"><label><span class="sr-only">昵称</span><input type="text" name="nickname" maxlength="40" placeholder="昵称" autocomplete="name" required></label><label><span class="sr-only">邮箱，可选</span><input type="email" name="email" maxlength="120" placeholder="邮箱（可选，不公开）" autocomplete="email"></label></div><label><span class="sr-only">评论内容</span><textarea name="content" maxlength="1000" placeholder="说点什么吧..."></textarea></label><div class="comment-tools"><button class="tool-toggle" type="button" data-tool-toggle aria-expanded="false">表情 / GIF</button><div class="tool-panel" data-tool-panel><div><div class="comment-tools__title">表情</div><div class="emoji-picker">${EMOJIS.map(e=>`<button class="emoji-button" type="button" data-emoji="${e}" aria-label="插入表情 ${e}">${e}</button>`).join('')}</div></div><div><div class="comment-tools__title">固定 GIF</div><div class="gif-picker">${GIFS.map(g=>`<button class="gif-option" type="button" data-gif-id="${g.id}" aria-label="选择 GIF：${esc(g.label)}"><img src="${g.url}" alt="${esc(g.label)}" loading="lazy"><span>${esc(g.label)}</span></button>`).join('')}</div></div></div><div class="selected-gif" data-selected-gif><span data-selected-gif-label></span><button class="selected-gif__remove" type="button" data-clear-gif>取消 GIF</button></div><input type="hidden" name="gifId" value=""></div><button class="blog-comments__submit" type="submit">发表评论</button><div class="blog-comments__message" data-comment-message role="status" aria-live="polite"></div></form><div class="blog-comments__list" data-comments-list></div>`}
function commentHtml(c){const p=unpack(c.content),g=gif(p.gif);return`${p.text?`<div class="comment-content">${esc(p.text)}</div>`:''}${g?`<div class="comment-gif"><img src="${g.url}" alt="${esc(g.label)}" loading="lazy"></div>`:''}`}
function show(list){const box=document.querySelector('[data-comments-list]');if(!box)return;if(!Array.isArray(list)||!list.length){box.innerHTML='<p class="blog-comments__empty">暂无评论，快来抢沙发吧。</p>';return}box.innerHTML=list.map(c=>`<article class="comment-item"><div class="comment-header"><span class="comment-author">${esc(c.nickname||'匿名访客')}</span><time class="comment-time" datetime="${esc(c.created_at)}">${time(c.created_at)}</time></div>${commentHtml(c)}</article>`).join('')}
async function loadComments(pageId=state.pagePath){const box=document.querySelector('[data-comments-list]');if(!box)return;if(!ok()){box.innerHTML='<p class="blog-comments__empty">评论系统还没有配置 Supabase。</p>';return}box.innerHTML='<p class="blog-comments__empty">正在加载评论...</p>';try{const q=`?select=id,nickname,content,created_at&page_path=eq.${encodeURIComponent(pageId)}&status=eq.approved&order=created_at.desc`;const r=await fetch(ep(q),{headers:headers()});if(!r.ok)throw new Error(`HTTP ${r.status}`);show(await r.json())}catch(e){console.error('加载评论失败:',e);box.innerHTML='<p class="blog-comments__empty">评论加载失败，请稍后再试。</p>'}}
function insertEmoji(t,e){const s=t.selectionStart,n=t.selectionEnd,v=t.value;t.value=`${v.slice(0,s)}${e}${v.slice(n)}`;t.focus();t.selectionStart=t.selectionEnd=s+e.length}
function selectGif(f,id){const g=gif(id),box=f.querySelector('[data-selected-gif]'),label=f.querySelector('[data-selected-gif-label]'),input=f.querySelector('input[name="gifId"]');input.value=g?g.id:'';box.classList.toggle('is-visible',!!g);label.textContent=g?`已选择 GIF：${g.label}`:'';f.querySelectorAll('[data-gif-id]').forEach(b=>b.classList.toggle('is-selected',b.dataset.gifId===input.value))}
async function submitComment(pageId=state.pagePath,form){if(!form)return;if(!ok()){msg('请先配置 Supabase 项目地址和 anon key。','error');return}const btn=form.querySelector('button[type="submit"]'),fd=new FormData(form),nickname=String(fd.get('nickname')||'').trim()||'匿名访客',email=String(fd.get('email')||'').trim(),content=String(fd.get('content')||'').trim(),gifId=String(fd.get('gifId')||'').trim();if(!content&&!gif(gifId)){msg('请输入评论内容，或选择一个 GIF。','error');return}if(content.length>1000){msg('评论内容不能超过 1000 个字符。','error');return}btn.disabled=true;btn.textContent='提交中...';msg('');try{const r=await fetch(ep(),{method:'POST',headers:headers({'Content-Type':'application/json',Prefer:'return=minimal'}),body:JSON.stringify({page_path:pageId,nickname,email:email||null,content:pack(content,gifId),user_agent:navigator.userAgent,status:COMMENT_STATUS_ON_SUBMIT})});if(!r.ok)throw new Error(await r.text());form.reset();selectGif(form,'');msg(COMMENT_STATUS_ON_SUBMIT==='pending'?'评论已提交，等待审核后显示。':'评论发布成功。','success');await loadComments(pageId)}catch(e){console.error('提交评论失败:',e);msg('提交失败，请检查 Supabase 配置或稍后再试。','error')}finally{btn.disabled=false;btn.textContent='发表评论'}}
function closePanel(form){const p=form.querySelector('[data-tool-panel]'),b=form.querySelector('[data-tool-toggle]');p.classList.remove('is-open');b.setAttribute('aria-expanded','false')}function bind(form){const t=form.querySelector('textarea[name="content"]'),panel=form.querySelector('[data-tool-panel]'),toggle=form.querySelector('[data-tool-toggle]');toggle.addEventListener('click',()=>{const open=!panel.classList.contains('is-open');panel.classList.toggle('is-open',open);toggle.setAttribute('aria-expanded',String(open))});form.querySelectorAll('[data-emoji]').forEach(b=>b.addEventListener('click',()=>{insertEmoji(t,b.dataset.emoji);closePanel(form)}));form.querySelectorAll('[data-gif-id]').forEach(b=>b.addEventListener('click',()=>{selectGif(form,b.dataset.gifId);closePanel(form)}));form.querySelector('[data-clear-gif]').addEventListener('click',()=>selectGif(form,''));document.addEventListener('click',e=>{if(!form.contains(e.target))closePanel(form)});document.addEventListener('keydown',e=>{if(e.key==='Escape')closePanel(form)})}
function initComments(){css();const c=document.querySelector('[data-blog-comments]')||document.getElementById('comment-section');if(!c)return;renderBox(c);const pageId=c.dataset.pagePath||state.pagePath;state.pagePath=pageId;const form=c.querySelector('[data-comment-form]');bind(form);form.addEventListener('submit',e=>{e.preventDefault();submitComment(pageId,form)});loadComments(pageId)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initComments);else initComments();
